export const vehiculos= [
    {
        id_publicacion: 1,
      	titulo: "Vendo mi Auto",
      	precio: 10000000,
      	marca: "Ford",
      	modelo: "Focus",
      	año: 2010,
      	kilometraje: 80000,
		transmision: "automatico",
		categoria: "Automovil",
		estado: "Usado",
		descripcion: "akshdklasjdlyebclasbclavcakjbdcñakegfbkdwbbcakba khbdclabdvae aecbaegcaiecbkaj aerlcal",
		imagen: "frontend\src\assets\img\vehiculo 7.png"
    },
    {
        id_publicacion: 2,
      	titulo: "Vendo mi Auto",
      	precio: 10000000,
      	marca: "Ford",
      	modelo: "Focus",
      	año: 2010,
      	kilometraje: 80000,
		transmision: "automatico",
		categoria: "Automovil",
		estado: "Usado",
		descripcion: "akshdklasjdlyebclasbclavcakjbdcñakegfbkdwbbcakba khbdclabdvae aecbaegcaiecbkaj aerlcal",
		imagen: "frontend\src\assets\img\vehiculo 7.png"
    },
    {
        id_publicacion: 3,
      	titulo: "Vendo mi Auto",
      	precio: 10000000,
      	marca: "Ford",
      	modelo: "Focus",
      	año: 2010,
      	kilometraje: 80000,
		transmision: "automatico",
		categoria: "Automovil",
		estado: "Usado",
		descripcion: "akshdklasjdlyebclasbclavcakjbdcñakegfbkdwbbcakba khbdclabdvae aecbaegcaiecbkaj aerlcal",
		imagen: "frontend\src\assets\img\vehiculo 7.png"
    },
    {
        id_publicacion: 4,
      	titulo: "Vendo mi Auto",
      	precio: 10000000,
      	marca: "Ford",
      	modelo: "Focus",
      	año: 2010,
      	kilometraje: 80000,
		transmision: "automatico",
		categoria: "Automovil",
		estado: "Usado",
		descripcion: "akshdklasjdlyebclasbclavcakjbdcñakegfbkdwbbcakba khbdclabdvae aecbaegcaiecbkaj aerlcal",
		imagen: "frontend\src\assets\img\vehiculo 7.png"
    },
    {
        id_publicacion: 5,
      	titulo: "Vendo mi Auto",
      	precio: 10000000,
      	marca: "Ford",
      	modelo: "Focus",
      	año: 2010,
      	kilometraje: 80000,
		transmision: "automatico",
		categoria: "Automovil",
		estado: "Usado",
		descripcion: "akshdklasjdlyebclasbclavcakjbdcñakegfbkdwbbcakba khbdclabdvae aecbaegcaiecbkaj aerlcal",
		imagen: "frontend\src\assets\img\vehiculo 7.png"
    },
    {
        id_publicacion: 6,
      	titulo: "Vendo mi Auto",
      	precio: 10000000,
      	marca: "Ford",
      	modelo: "Focus",
      	año: 2010,
      	kilometraje: 80000,
		transmision: "automatico",
		categoria: "Automovil",
		estado: "Usado",
		descripcion: "akshdklasjdlyebclasbclavcakjbdcñakegfbkdwbbcakba khbdclabdvae aecbaegcaiecbkaj aerlcal",
		imagen: "frontend\src\assets\img\vehiculo 7.png"
    }
]
